---
title: "Final Completion Prob"
author: "Jill Reiner"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyverse)
library(tidyr)
library(stringr)
library(janitor)
library(mgcv)
library(caret)
library(car)
```

```{r}
min_opp_dists$pos_def[min_opp_dists$name_def == "Jessie Bates"] <- "S"
min_opp_dists$pos_def[min_opp_dists$name_def == "Minkah Fitzpatrick"] <- "S"
min_opp_dists$pos_def[min_opp_dists$name_def == "Derwin James"] <- "S"
min_opp_dists$pos_def[min_opp_dists$name_def == "Holton Hill"] <- "DB"
min_opp_dists$pos_def[min_opp_dists$name_def == "Isaiah Johnson"] <- "S"
min_opp_dists$pos_def[min_opp_dists$name_def == "Maurice Smith"] <- "DB"

min_opp_dists$name_def[min_opp_dists$name_def == "Trey Walker"] <- "Tracy Walker"
```

```{r}
intended_rec_cp <- min_opp_dists %>% 
  filter(pos_off %in% c("WR", "TE", "RB", "FB", "HB"),
         #pos_def %in% c("CB", "DB", "FS", "S", "SS"),
         !is.na(route), #filtering to those running routes
         is_targ_receiver == 1,
         grepl("pass_outcome_", event)) %>% 
  drop_na(dist_to_qb_off) %>%
  mutate(pass_success = ifelse(event %in% c("pass_outcome_caught", "pass_outcome_touchdown"), 1,0))

intended_rec_cp$pass_success = as.factor(intended_rec_cp$pass_success)
```

```{r}
times_targeted <- intended_rec_cp %>%
  select(game_id, play_id, name_def, nfl_id_def) %>%
  group_by(name_def, nfl_id_def) %>%
  summarise(times_targ = n()) %>%
  ungroup()
```

```{r}
set.seed(1220)

train_i <- createDataPartition(y = intended_rec_cp$pass_success, p = 0.75, list = FALSE) %>% as.numeric()

train_cp_data <- intended_rec_cp[train_i,]
test_cp_data <- intended_rec_cp[-train_i,]
```

```{r}
table(train_cp_data$pass_success)
table(test_cp_data$pass_success)
```

```{r}
set.seed(1999)

init_cp_train <- train(pass_success ~ closest_opp_distance + dist_to_qb_off + dist_to_qb_def + x_off + y_off + s_off*s_def + dir_off*dir_def + o_off*o_def + dis_off*dis_def + yardline_number, 
                            data = train_cp_data, method = "glm",
                            trControl = trainControl("cv", number = 10),
                            preProcess = c("center", "scale"),
                            na.action = na.omit,
                            family = "binomial")

init_cp_train
```

```{r}
ggplot(varImp(init_cp_train))
```

```{r}
init_cp <- glm(pass_success ~ closest_opp_distance + dist_to_qb_off + dist_to_qb_def + x_off + y_off + s_def, 
               family = "binomial", data = test_cp_data)

summary(init_cp)
```

```{r}
intended_rec_cp$cp_preds <- predict(init_cp, newdata = intended_rec_cp, type = "response")

intended_rec_cp$cp_preds2 <- as.factor(ifelse(intended_rec_cp$cp_preds > .5, "1", "0"))

confusionMatrix(intended_rec_cp$cp_preds2, intended_rec_cp$pass_success)
```

```{r}
mean(ifelse(fitted(init_cp) < 0.5, 0, 1) != intended_rec_cp$pass_success) #misclassification rate

library(DescTools)
DescTools::BrierScore(init_cp)
```


```{r}
summarized_cp <- intended_rec_cp %>%
  mutate(pass_success = as.numeric(pass_success),
    comp_difference = cp_preds - pass_success)
```

overall completions taken away
```{r}
summarized_cp <- intended_rec_cp %>%
  mutate(pass_success = as.numeric(as.character(pass_success)),
    comp_difference = as.numeric(as.character(cp_preds - pass_success))) %>%
  group_by(name_def, nfl_id_def, pos_def) %>%
  summarise(completions_taken_away = sum(comp_difference))
```

pass forward to pass arrived
```{r}
intended_rec_pf_to_pa <- min_opp_dists %>% #lets just start with the intended receiver and get those CPs
  filter(pos_off %in% c("WR", "TE", "RB", "FB", "HB"),
         #pos_def %in% c("CB", "DB", "FS", "S", "SS"),
         !is.na(route),
         is_targ_receiver == 1,
         event == "pass_forward" | event == "pass_arrived") %>%
  mutate(pass_success = ifelse(event %in% c("pass_outcome_caught", "pass_outcome_touchdown"), 1,0))

intended_rec_pf_to_pa$pass_success = as.factor(intended_rec_pf_to_pa$pass_success)
```

```{r}
intended_rec_pf_to_pa$cp_preds <- predict(init_cp, newdata = intended_rec_pf_to_pa, type = "response")
```

```{r}
same_defenders_intended_rec <- intended_rec_pf_to_pa %>%
  group_by(game_id, play_id, name_off) %>%
  mutate(unique_defender = n_distinct(nfl_id_def)) %>%
  ungroup() %>%
  filter(unique_defender == 1)
```

```{r}
summarized_intended_receivers <- same_defenders_intended_rec %>%
  group_by(game_id, play_id, name_off) %>%
  mutate(cp_diff =  cp_preds - lag(cp_preds, default = cp_preds[1])) %>%
  ungroup()
```

closeout
```{r}
comp_pred_stats_pf_to_arrival <- summarized_intended_receivers %>%
  group_by(nfl_id_def, name_def, pos_def) %>%
  summarise(closeout = sum(cp_diff)) #%>%
  #left_join(times_targeted, by = c("nfl_id_def", "name_def"))
```

pass arrived to pass outcome x
```{r}
intended_rec_pa_to_po <- min_opp_dists %>% #lets just start with the intended receiver and get those CPs
  filter(pos_off %in% c("WR", "TE", "RB", "FB", "HB"),
         #pos_def %in% c("CB", "DB", "FS", "S", "SS"),
         !is.na(route),
         is_targ_receiver == 1,
         event == "pass_arrived" | grepl("pass_outcome_", event)) %>%
  mutate(pass_success = ifelse(event %in% c("pass_outcome_caught", "pass_outcome_touchdown"), 1,0))

intended_rec_pa_to_po$pass_success = as.factor(intended_rec_pa_to_po$pass_success)
```

```{r}
intended_rec_pa_to_po$cp_preds <- predict(init_cp, newdata = intended_rec_pa_to_po, type = "response")
```

```{r}
same_defenders_intended_rec <- intended_rec_pa_to_po %>% #same defenders from arrival to outcome
  group_by(game_id, play_id, name_off) %>%
  mutate(unique_defender = n_distinct(nfl_id_def)) %>%
  ungroup() %>%
  filter(unique_defender == 1)
```

```{r}
summarized_intend_pa_po <- same_defenders_intended_rec %>%
  group_by(game_id, play_id, name_off) %>%
  mutate(cp_diff = cp_preds - lag(cp_preds, default = cp_preds[1])) %>%
  ungroup()
```

passes defended
```{r}
comp_pred_stats <- summarized_intend_pa_po %>%
  group_by(nfl_id_def, name_def, pos_def) %>%
  summarise(passes_defended = sum(cp_diff)) #%>%
  #left_join(times_targeted, by = c("nfl_id_def", "name_def"))
```

overall pass forward to pass outcome
```{r}
intended_rec_pf_to_po <- min_opp_dists %>% #lets just start with the intended receiver and get those CPs
  filter(pos_off %in% c("WR", "TE", "RB", "FB", "HB"),
         #pos_def %in% c("CB", "DB", "FS", "S", "SS"),
         !is.na(route),
         is_targ_receiver == 1,
         event == "pass_forward" | grepl("pass_outcome_", event)) %>%
  mutate(pass_success = ifelse(event %in% c("pass_outcome_caught", "pass_outcome_touchdown"), 1,0))

intended_rec_pf_to_po$pass_success = as.factor(intended_rec_pf_to_po$pass_success)
```

```{r}
intended_rec_pf_to_po$cp_preds <- predict(init_cp, newdata = intended_rec_pf_to_po, type = "response")
```

```{r}
same_defenders_intended_rec_pf_to_po <- intended_rec_pf_to_po %>%
  group_by(game_id, play_id, name_off) %>%
  mutate(unique_defender = n_distinct(nfl_id_def)) %>%
  ungroup() %>%
  filter(unique_defender == 1)
```

```{r}
summarized_intend_pf_po <- same_defenders_intended_rec_pf_to_po %>%
  group_by(game_id, play_id, name_off) %>%
  mutate(cp_diff = cp_preds - lag(cp_preds, default = cp_preds[1])) %>%
  ungroup()
```

pass forward to pass outcome
```{r}
comp_pred_stats_pf_to_po <- summarized_intend_pf_po %>%
  group_by(nfl_id_def, name_def, pos_def) %>%
  summarise(total_passes_defended = sum(cp_diff)) #%>%
  #left_join(times_targeted, by = c("nfl_id_def", "name_def"))
```