---
title: "Initial Set Up"
author: "Jill Reiner"
date: "10/19/2020"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(tidyverse)
library(tidyr)
library(stringr)
library(janitor)
```

```{r}
library(usethis)
use_git_config(user.name = "Jill Reiner", user.email = "reiner_j1@denison.edu")
```

```{r message=FALSE}
df_games <- read_csv("../Data/games.csv") #schedule info
df_players <- read_csv("../Data/players.csv") #player info
df_plays <- read_csv("../Data/plays.csv") #play by play info
df_targeted_receiver <- read_csv("../Data/targetedReceiver.csv") #targeted receiver info
#df_week1coverages <- read_csv("../Data/coverages_week1.csv") #week 1 coverages
```

```{r}
weeks <- seq(1,17)
df_tracking <- data.frame() #empty df, will append all weeks
```

```{r message=FALSE}
for(week in weeks) { #this chunk killed my comp :)
  all_weeks <- read_csv(paste0("../Data/week", week, ".csv"))
  df_tracking <- bind_rows(all_weeks, df_tracking) 
}
```

```{r}
df_games <- df_games %>%
  clean_names() %>%
  select(-game_time_eastern)

df_players <- df_players %>%
  clean_names()

df_plays_passes <- df_plays %>%
  clean_names() %>%
  filter(play_type == "play_type_pass") %>%
  select(-penalty_codes, -penalty_jersey_numbers, -is_defensive_pi) %>%
  mutate(pass_success = ifelse(pass_result == "C", 1, 0))

df_targeted_receiver <- df_targeted_receiver %>%
  clean_names() %>%
  na.omit()

df_tracking <- df_tracking %>%
  clean_names() %>%
  select(-time) %>%
  filter(event != "None")

#df_week1coverages <- df_week1coverages %>%
  #clean_names() %>%
  #mutate(coverage_simp = case_when(str_detect(coverage, "Man") ~ "man",
                                   #str_detect(coverage, "Zone") ~ "zone")) %>%
  #select(-coverage)
```

```{r}
df_tracking <- df_tracking %>%
  mutate(x = ifelse(play_direction == "left", 120-x, x), #standardize coords
         y = ifelse(play_direction == "left", 160/3 - y, y))
```

```{r}
tracking_and_plays <- inner_join(df_tracking, df_plays_passes, 
                               by = c("game_id" = "game_id",
                                     "play_id" = "play_id"))
```

```{r}
#tracking_and_plays_w_coverage <- inner_join(tracking_and_plays, df_week1coverages, #can only run this if only working with week 1
                                            #by = c("game_id" = "game_id",
                                                   #"play_id" = "play_id"))
```

```{r}
players_target_receiver_info <- left_join(df_targeted_receiver, df_players, 
                                           by = c("target_nfl_id" = "nfl_id"))

players_target_receiver_info <- players_target_receiver_info %>%
  select(-height, -weight, -birth_date, -college_name, -position, -display_name)
```

```{r}
tracking_plays_players <- inner_join(players_target_receiver_info, tracking_and_plays, #tracking_and_plays_w_coverage,
                                     by = c("game_id" = "game_id",
                                            "play_id" = "play_id"))
```

```{r}
df_games_homeaway_info <- df_games %>%
  select(game_id, home_team_abbr, visitor_team_abbr) #need these to see which team is on O/D

tracking_plays_games <- inner_join(tracking_plays_players, df_games_homeaway_info,
                            by = c("game_id" = "game_id"))
```

```{r}
full_tracking <- tracking_plays_games %>%
  mutate(side_of_ball = ifelse(#player is home and home has ball
                              ((team == "home") & 
                              (possession_team == home_team_abbr)) |
                              
                              #player is away and away has ball
                              ((team == "away") &
                              (possession_team == visitor_team_abbr)), 
                              "offense",
                              "defense"),
         defensive_team = ifelse(possession_team == home_team_abbr,
                                              visitor_team_abbr,
                                              home_team_abbr),
         is_defender = ifelse(side_of_ball == "defense", 1, 0),
         is_targ_receiver = ifelse(target_nfl_id == nfl_id, 1, 0)) %>%
  group_by(game_id, play_id, frame_id) %>%
  mutate(footballInPlay = sum(display_name == "Football") > 0) %>%
  filter(footballInPlay) %>%
  mutate(x_ball = x[display_name == "Football"],
         y_ball = y[display_name == "Football"]) %>%
  ungroup()
```

```{r}
qb <- full_tracking %>% #will use this to find distance to qb
  group_by(game_id, play_id, frame_id) %>%
  filter(position == "QB") %>%
  select(game_id, play_id, frame_id, x, y) %>%
  rename(x_qb = x,
         y_qb = y)

full_tracking <- left_join(full_tracking, qb, by = c("game_id",
                                                     "play_id",
                                                     "frame_id"))
```

```{r}
receiver <- full_tracking %>%
  filter(is_targ_receiver == 1) %>%
  select(game_id, play_id, frame_id, x, y) %>%
  rename(x_targ = x,
         y_targ = y)

full_tracking <- left_join(full_tracking, receiver, by = c("game_id",
                                                           "play_id",
                                                           "frame_id"))
```

```{r}
full_tracking <- full_tracking %>%
  mutate(x_rel_to_ball = x - x_ball,
         y_rel_to_ball = y - y_ball,
         dist_to_ball = sqrt(x_rel_to_ball^2 + y_rel_to_ball^2),
         x_rel_to_qb = x - x_qb,
         y_rel_to_qb = y - y_qb,
         dist_to_qb = sqrt(x_rel_to_qb^2 + y_rel_to_qb^2),
         x_rel_to_targ = x - x_targ,
         y_rel_to_targ = y - y_targ,
         dist_to_targ = sqrt(x_rel_to_targ^2 + y_rel_to_targ^2)) %>%
  filter(!is.na(x_qb), !is.na(x_targ)) #plays without qb or target
```

```{r}
table(full_tracking$play_type)
```





