---
title: "Summary"
author: "Jill Reiner"
date: "12/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mclust)
library(protoclust)
library(broom)
library(gghighlight)
library(RColorBrewer)
```

```{r}
snaps_played <- full_tracking %>%
  filter(event == "ball_snap", team != "football", side_of_ball == "defense") %>%
  add_count(nfl_id) %>%
  select(game_id, play_id, display_name, nfl_id, n) %>%
  group_by(display_name, nfl_id) %>%
  summarise(snaps_played = n()) %>%
  ungroup() %>%
  rename(nfl_id_def = nfl_id, name_def = display_name)
```

```{r}
full_def_stats <- comp_pred_stats %>%
  full_join(targ_pred_stats, by = c("nfl_id_def", "name_def", "pos_def")) %>%
  full_join(comp_pred_stats_pf_to_arrival, by = c("nfl_id_def", "name_def", "pos_def")) %>%
  #full_join(comp_pred_stats_pf_to_po, by = c("nfl_id_def", "name_def", "pos_def")) %>%
  full_join(snaps_played, by = c("nfl_id_def", "name_def")) %>%
  full_join(times_targeted, by = c("nfl_id_def", "name_def")) %>%
  ungroup()
```

```{r}
full_def_stats %>%
  ggplot(aes(x = snaps_played)) +
  stat_ecdf() +
  theme_bw() +
  labs(x = "Snaps played",
       y = "Proportion of defenders") +
  geom_vline(xintercept = 35,
             linetype = "dashed",
             color = "darkred")
```

```{r}
filtered_def_stats <- full_def_stats %>%
  filter(snaps_played >= 40, times_targ >= 25) %>%
  mutate_at(scale, .vars = vars(passes_defended, targets_averted, closeout)) %>%
  na.omit()
```

```{r}
which(is.na(filtered_def_stats))
```


```{r}
def_mclust <- Mclust(dplyr::select(filtered_def_stats, targets_averted, closeout, passes_defended))
```

```{r}
summary(def_mclust)
```

```{r}
plot(def_mclust, what = 'classification')
```

```{r}
table("Positions" = filtered_def_stats$pos_def,
      "Clusters" = def_mclust$classification)
```

```{r}
filtered_def_stats %>%
  mutate(cluster =
           def_mclust$classification,
         uncertainty =
           def_mclust$uncertainty) %>%
  group_by(cluster) %>%
  arrange(desc(uncertainty)) %>%
  slice(1:10) %>%
  ggplot(aes(y = uncertainty, 
             x = reorder(name_def,
                         uncertainty))) +
  geom_point() +
  coord_flip() + 
  facet_wrap(~ cluster, 
             scales = 'free_y', nrow = 3) +
  theme_bw()
```

```{r}
gmm_preds <- as.data.frame(predict(def_mclust, select(filtered_def_stats, targets_averted, closeout, passes_defended))) 

gmm_preds_aug <- augment(def_mclust, select(filtered_def_stats, targets_averted, closeout, passes_defended)) 

gmm_preds_aug$nfl_id_def <- filtered_def_stats$nfl_id_def 
gmm_preds_aug$name_def <- filtered_def_stats$name_def
gmm_preds_aug$pos_def <- filtered_def_stats$pos_def
```

```{r}
gmm_preds_aug %>%
  select(nfl_id_def, name_def, pos_def, .class, .uncertainty) %>% # select columns describing the player / cluster
  filter(.class == 2, pos_def == "CB") %>% # filter to an individual cluster
  arrange(.uncertainty) %>% # sort by probability
  head(15)
```

```{r}
filtered_def_stats$clust <- def_mclust$classification
```

```{r}
m_centers <- def_mclust$parameters$mean %>%
  t() %>%
  as.data.frame()

m_centers$Cluster <- c('Cluster 1', 'Cluster 2', 'Cluster 3')

m_centers <- m_centers %>%
  pivot_longer(!Cluster, names_to = 'feature', values_to = 'z_value')

m_centers$feature <- factor(m_centers$feature, levels = c('targets_averted', 'closeout','passes_defended'))
```

```{r}
gmm_plot <- m_centers %>%
  ggplot(aes(x = feature, y = z_value, color = Cluster)) +
  geom_point(size = 1.8) + 
  geom_line() +
  facet_wrap(~ Cluster) +
  gghighlight(use_direct_label = FALSE) +
  labs(x = "Feature", y = "Scaled Group Center", 
       title = "Visualizing Defender Types: Model Based Cluster Makeups") + 
  scale_x_discrete(labels = c("Targets Averted", "Closeout", "Passes Defended"), guide = guide_axis(angle = 45)) +
  scale_color_brewer(palette = "Set2") +
  theme_bw() +
  theme(legend.position = "none", strip.text = element_text(face='bold'))

#ggsave("gmm_plot.png", gmm_plot, height = 5)
```


```{r}
multidim_clust <- protoclust(dist(dplyr::select(filtered_def_stats, hypothetical_passes_defended, completions_taken_away, tackles_over_expected, targets_averted, hypothetical_closeout)))

multidim_clust_cut <- protocut(multidim_clust, k = 3)
table("Positions" = filtered_def_stats$pos_def,
      "Clusters" = multidim_clust_cut$cl)
```

```{r}
def_minimax <- protoclust(dist(
    dplyr::select(filtered_def_stats, hypothetical_passes_defended, completions_taken_away, tackles_over_expected, targets_averted, hypothetical_closeout)))
plot(def_minimax)
```

```{r}
minimax_player_clusters <-
  protocut(def_minimax, k = 3)

proto <- minimax_player_clusters$protos

filtered_def_stats[minimax_player_clusters$protos, ]
```


